#!/usr/bin/env bash
# This script displays information about subdomains.

# Check if the required arguments are provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Function to display information about a subdomain
display_info() {
    domain="$1"
    subdomain="$2"

# If subdomain is not provided, display information for default subdomains
if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

# Iterate over the subdomains and display information
for sub in "${subdomains[@]}"; do
    record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $4}')
    destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $5}')
    echo "The subdomain $sub a $record_type record and points to $destination"
done
}

display_info "$1" "$2"
