#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a new server block for redirection
sudo sh -c 'echo "
server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/redirect'

# Enable the redirection server block
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove the default server block
sudo rm /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
