#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx for redirection
sudo sed -i '/location \/ {/a \\tlocation /redirect_me {\\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
