#!/usr/bin/env bash
# Install nginx if not already installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Configure Nginx for custom 404 HTML page
echo "Ceci n'est pas une page

" | sudo tee /usr/share/nginx/html/404.html > /dev/null


sudo sed -i "/listen 80 default_server;/a error_page 404 /404.html;\nlocation = /404.html {\n    root /usr/share/nginx/html;\n    internal;\n}" /etc/nginx/sites-enabled/default

# Test and Restart Nginx to apply changes
sudo nginx -t && sudo service nginx restart
