#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Use sed to insert lines for custom 404 page in Nginx configuration
sudo sed -i '/server_name _;/a \\n\tlocation /404 {\n\t\tinternal;\n\t\treturn 404 "Ceci n'est pas une page";\n\t}\n\terror_page 404 /404;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
