#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Update Nginx configuration
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Update Nginx configuration to add the redirection
sudo sed -i '0,/\blocation \/ {/&\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Update Nginx configuration to add the custom 404 page
sudo sed -i '0,/\blocation \/ {/&\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Update Nginx configuration to add the custom header after the first occurrence of location / {
sudo sed -i '0,/\blocation \/ {/s/\blocation \/ {/&\n\tadd_header X-Served-By $hostname;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
