#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy

echo "frontend web_front
        bind *:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 445286-web-01 35.153.98.151:80 check
        server 445286-web-02 54.146.56.220:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Start and enable the HAProxy service
sudo systemctl start haproxy
sudo systemctl enable haproxy
