#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy

echo "frontend web_front
        bind 0.0.0.0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server web-01 445286-web-01:80 check
        server web-02 445286-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Start and enable the HAProxy service
sudo systemctl start haproxy
sudo systemctl enable haproxy
