#!/usr/bin/env bash
# Bash script to ping an IP address passed as an argument.

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# IP address passed as an argument
ip_address=$1

# Ping the IP address 5 times
ping_result=$(ping -c 5 "$ip_address")

# Display the ping results
echo "$ping_result"
