#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Install Nginx (if not already installed)
apt-get update
apt-get install -y nginx

# Ensure Nginx is running
service nginx start

# Configure Nginx to listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Reload Nginx configuration
service nginx restart
