#!/usr/bin/env bash
# A Bash script that performs the specific actions.
# To handle SIGQUIT signal
# Function to perform cleanup and exit
function cleanup_and_exit() {
  rm /var/run/myscript.pid
  exit
}
# To handle SIGTERM signal
trap "echo I hate the kill command;cleanup_and_exit" SIGTERM
# To handle SIGINT signal
trap "echo Y U no love me?!;cleanup_and_exit" SIGINT
# Create the PID file
echo $$ > /var/run/holbertonscript.pid
# Infinite loop
while true; do
  echo "To infinity and beyond"
  sleep 2
done
