#!/usr/bin/env bash
# Function to start manage_my_process
function start_process() {
  if [ -f "/var/run/my_process.pid" ]; then
    echo "manage_my_process is already started."
    exit 1
  fi

  ./manage_my_process &
  echo $! > /var/run/my_process.pid
  echo "manage_my_process started"
}
# Function to stop manage_my_process
function stop_process() {
  if [ -f "/var/run/my_process.pid" ]; then
    pid=$(cat /var/run/my_process.pid)
    rm /var/run/my_process.pid
    kill $pid
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running."
  fi
}
# Function to restart manage_my_process
function restart_process() {
  stop_process
  start_process
  echo "manage_my_process restarted"
}
# Check for the command-line argument
if [ $# -eq 1 ]; then
  case "$1" in
    start)
      start_process
      ;;
    stop)
      stop_process
      ;;
    restart)
      restart_process
      ;;
    *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
      ;;
  esac
else
  echo "Usage: $0 {start|stop|restart}"
  exit 1
fi
