#!/usr/bin/env bash
# Trap the SIGTERM signal and execute the specified command
trap 'echo "I am invincible!!!"' SIGTERM
# Infinite loop to display a message and sleep for 2 seconds between iterations
while true; do
    echo "To infinity and beyond"
    sleep 2
done
