#!/usr/bin/env bash
# Displays the content of the file /etc/passwd in a story format.

while IFS=: read -r username _ uid gid gecos home shell; do
  echo "The user $username is part of the $gid gang, lives in $home, and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $gecos"
done < /etc/passwd
