#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements.

# Change localhost resolution to 127.0.0.2
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts

# Change facebook.com resolution to 8.8.8.8
sudo sed -i 's/157.240.11.35 facebook.com/8.8.8.8 facebook.com/' /etc/hosts
