#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements.

# Change localhost resolution to 127.0.0.2
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
# Change facebook.com resolution to 8.8.8.8
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
