#!/usr/bin/env bash
# Start the Docker container

docker run -p 8080:80 -d holbertonschool/265-0
docker exec -it <container_id> /bin/bash
cd /etc/apache2/sites-available
vi 000-default.conf

service apache2 restart
