#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Update the nginx configuration to run as the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf

# Update the default site configuration to listen on port 8080
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2

# Restart Nginx to apply changes
su nginx -s /bin/bash -c 'service nginx restart'
