#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen 80;/ a \    listen 8080;' /etc/nginx/sites-available/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
