#!/usr/bin/env bash
# This script creates an RSA key pair

# Specify the key name
key_name="school"

# Generate the RSA key pair with 4096 bits and protect it with passphrase "betty"
ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$key_name" -N "betty"
